
development:
  adapter: postgresql
  encoding: unicode
  database: list_back_end_dev

test:
  adapter: postgresql
  encoding: unicode
  database: list_back_end_test


production:
  adapter: postgresql
  encoding: unicode
  database: list_back_end_prod